CREATE DATABASE IF NOT EXISTS hostel_management;
USE hostel_management;

-- ADMIN
CREATE TABLE ADMIN (
  admin_id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- WARDEN
CREATE TABLE WARDEN (
  Warden_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Contact VARCHAR(20) NOT NULL,
  Address TEXT NOT NULL
);

-- HOSTEL
CREATE TABLE HOSTEL (
  Hostel_name VARCHAR(100) PRIMARY KEY,
  Hostel_Location VARCHAR(255) NOT NULL,
  Room_no INT NOT NULL,
  Warden_ID INT,
  FOREIGN KEY (Warden_ID) REFERENCES WARDEN(Warden_ID)
    ON DELETE SET NULL ON UPDATE CASCADE
);

-- ROOMS
CREATE TABLE ROOMS (
  Room_No INT PRIMARY KEY,
  Floor_no INT NOT NULL,
  Room_Type ENUM('Single', 'Double', 'Triple') NOT NULL,
  S_ID INT DEFAULT NULL
);

-- STUDENT
CREATE TABLE STUDENT (
  S_ID INT PRIMARY KEY AUTO_INCREMENT,
  Fname VARCHAR(50) NOT NULL,
  Minit CHAR(1),
  Lname VARCHAR(50) NOT NULL,
  GENDER ENUM('M', 'F', 'Other') NOT NULL,
  ADDRESS TEXT NOT NULL,
  Room_No INT DEFAULT NULL,
  FOREIGN KEY (Room_No) REFERENCES ROOMS(Room_No)
    ON DELETE SET NULL ON UPDATE CASCADE
);

-- Add FK after table creation
ALTER TABLE ROOMS
  ADD CONSTRAINT fk_rooms_student
  FOREIGN KEY (S_ID) REFERENCES STUDENT(S_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- PAYMENT
CREATE TABLE PAYMENT (
  Payment_ID INT PRIMARY KEY AUTO_INCREMENT,
  Paymentdate DATE NOT NULL,
  Mode ENUM('Cash', 'UPI', 'Card', 'Bank Transfer') NOT NULL,
  Student_ID INT NOT NULL,
  FOREIGN KEY (Student_ID) REFERENCES STUDENT(S_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- STUDENT AUTH
CREATE TABLE STUDENT_AUTH (
  student_auth_id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  S_ID INT DEFAULT NULL,
  is_verified BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (S_ID) REFERENCES STUDENT(S_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- BOOKINGS
CREATE TABLE BOOKINGS (
  booking_id INT PRIMARY KEY AUTO_INCREMENT,
  S_ID INT NOT NULL,
  Room_No INT NOT NULL,
  Hostel_name VARCHAR(100) NOT NULL,
  status ENUM('pending', 'approved', 'rejected', 'cancelled') DEFAULT 'pending',
  booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved_at TIMESTAMP NULL DEFAULT NULL,
  FOREIGN KEY (S_ID) REFERENCES STUDENT(S_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (Room_No) REFERENCES ROOMS(Room_No)
    ON DELETE CASCADE,
  FOREIGN KEY (Hostel_name) REFERENCES HOSTEL(Hostel_name)
    ON DELETE CASCADE
);

-- MINIMAL SAMPLE DATA

INSERT INTO ADMIN (username, email, password)
VALUES ('admin', 'admin@hostel.com', '$2b$12$8swmA8Qw6a6YY4cF2xBzCO4GsYxJZGfQxAZTJQw8wM14jArlTc95y');

INSERT INTO WARDEN (Name, Contact, Address)
VALUES ('Aarav Mehta', '9876543210', 'Lake View Road');

INSERT INTO HOSTEL (Hostel_name, Hostel_Location, Room_no, Warden_ID)
VALUES ('Alpha Hostel', 'North Campus', 100, 1);

INSERT INTO ROOMS (Room_No, Floor_no, Room_Type)
VALUES (101, 1, 'Single');

INSERT INTO STUDENT (Fname, Lname, GENDER, ADDRESS, Room_No)
VALUES ('Aman', 'Verma', 'M', 'Delhi', 101);

UPDATE ROOMS SET S_ID = 1 WHERE Room_No = 101;

INSERT INTO PAYMENT (Paymentdate, Mode, Student_ID)
VALUES ('2026-04-01', 'UPI', 1);